"""
라이더-웨이트 메이저 아르카나 22장 데이터.
이미지: static/tarot/major/{id:02d}_{slug}.jpg
"""

TAROT_MAJOR = [
    {
        "id": 0, "slug": "fool",
        "name": "The Fool", "name_kr": "광대",
        "wiki_file": "RWS_Tarot_00_Fool.jpg",
        "keywords": ["새 시작", "자유", "순수", "모험"],
        "upright":  "새로운 여정의 출발선에 섰습니다. 두려움 없이 한 걸음 내디뎌 보세요. 가벼운 마음과 호기심이 가장 큰 무기입니다.",
        "reversed": "무모함과 충동을 경계하세요. 발을 내딛기 전에 한 번 더 점검하면 좋은 길이 보입니다.",
        "do_up":    "호기심 가는 일에 가볍게 첫 발 내디뎌 보기",
        "dont_up":  "결과부터 따지며 망설이기",
        "do_rev":   "한 번 더 점검하고 출발하기",
        "dont_rev": "충동적으로 큰 결정 내리기",
    },
    {
        "id": 1, "slug": "magician",
        "name": "The Magician", "name_kr": "마법사",
        "wiki_file": "RWS_Tarot_01_Magician.jpg",
        "keywords": ["창조력", "의지", "실행력", "잠재력"],
        "upright":  "필요한 도구가 이미 손에 있습니다. 의지와 실행이 만나면 원하는 흐름이 만들어지는 날입니다.",
        "reversed": "재능을 잘못 쓰고 있지 않은지 돌아보세요. 진심이 빠진 화려함은 오래 가지 않습니다.",
        "do_up":    "미뤄둔 일을 오늘 단 10분이라도 시작하기",
        "dont_up":  "준비만 반복하며 손을 놓기",
        "do_rev":   "본질이 무엇인지 스스로에게 묻기",
        "dont_rev": "보여주기식 화려함에 시간 쓰기",
    },
    {
        "id": 2, "slug": "high_priestess",
        "name": "The High Priestess", "name_kr": "여사제",
        "wiki_file": "RWS_Tarot_02_High_Priestess.jpg",
        "keywords": ["직관", "내면", "신비", "잠재의식"],
        "upright":  "조용히 마음을 들여다보세요. 말하지 않아도 알 수 있는 흐름이 있고, 직관이 좋은 길을 알려줍니다.",
        "reversed": "감정을 너무 숨기고 있지 않은지 살펴보세요. 작은 표현이 큰 오해를 풀어줍니다.",
        "do_up":    "혼자 산책하며 마음 정리하는 시간",
        "dont_up":  "시끄러운 자리에서 큰 결정 내리기",
        "do_rev":   "한 줄이라도 마음 표현해 보기",
        "dont_rev": "혼자 다 안고 끙끙대기",
    },
    {
        "id": 3, "slug": "empress",
        "name": "The Empress", "name_kr": "여황제",
        "wiki_file": "RWS_Tarot_03_Empress.jpg",
        "keywords": ["풍요", "창조", "사랑", "돌봄"],
        "upright":  "풍요와 사랑의 기운이 풍성한 날입니다. 정성껏 가꾸는 일이 자연스럽게 결실로 이어집니다.",
        "reversed": "주변에 너무 많이 베풀어 본인이 비어가지 않도록 균형을 맞추세요.",
        "do_up":    "좋아하는 사람에게 따뜻한 한마디",
        "dont_up":  "자기 자신 챙기는 일을 미루기",
        "do_rev":   "본인 컵부터 채우는 시간 갖기",
        "dont_rev": "에너지 다 퍼주기",
    },
    {
        "id": 4, "slug": "emperor",
        "name": "The Emperor", "name_kr": "황제",
        "wiki_file": "RWS_Tarot_04_Emperor.jpg",
        "keywords": ["권위", "안정", "리더십", "구조"],
        "upright":  "체계와 안정이 힘이 됩니다. 결정과 책임을 자기 자리에서 분명히 잡으면 흐름이 정돈됩니다.",
        "reversed": "고집이나 통제 욕구가 관계를 경직시킬 수 있으니 부드러움을 더해주세요.",
        "do_up":    "미뤄온 결정 하나 분명히 내리기",
        "dont_up":  "어물쩍 넘기며 책임 흘리기",
        "do_rev":   "한 발 물러나 다른 의견 들어주기",
        "dont_rev": "내 방식만 맞다고 고집하기",
    },
    {
        "id": 5, "slug": "hierophant",
        "name": "The Hierophant", "name_kr": "교황",
        "wiki_file": "RWS_Tarot_05_Hierophant.jpg",
        "keywords": ["전통", "가르침", "지혜", "신뢰"],
        "upright":  "검증된 길과 어른의 조언이 도움이 됩니다. 새로움보다 깊이를 다지는 하루가 좋습니다.",
        "reversed": "낡은 규칙에서 벗어나 본인만의 길을 검토할 시기일 수 있습니다.",
        "do_up":    "신뢰하는 선배에게 조언 구하기",
        "dont_up":  "혼자만의 판단으로 끙끙대기",
        "do_rev":   "낡은 규칙은 다시 살펴보기",
        "dont_rev": "권위에 무조건 따르기",
    },
    {
        "id": 6, "slug": "lovers",
        "name": "The Lovers", "name_kr": "연인",
        "wiki_file": "RWS_Tarot_06_Lovers.jpg",
        "keywords": ["사랑", "선택", "결합", "조화"],
        "upright":  "마음이 끌리는 방향에 진실이 있습니다. 중요한 선택의 갈림에서 가슴의 답을 따라보세요.",
        "reversed": "관계나 결정에서 균형이 흔들리고 있는지 점검하세요. 솔직한 대화가 답입니다.",
        "do_up":    "마음 가는 쪽에 솔직히 표현하기",
        "dont_up":  "양쪽 다 챙기려고 결정 미루기",
        "do_rev":   "솔직한 대화 한 번 시도하기",
        "dont_rev": "침묵으로 오해 키우기",
    },
    {
        "id": 7, "slug": "chariot",
        "name": "The Chariot", "name_kr": "전차",
        "wiki_file": "RWS_Tarot_07_Chariot.jpg",
        "keywords": ["의지", "추진", "승리", "집중"],
        "upright":  "흩어진 에너지를 한 방향으로 모으면 결과가 명확합니다. 추진력이 가장 빛나는 날입니다.",
        "reversed": "방향을 잃은 추진은 위험합니다. 잠시 멈춰 목적을 다시 세우세요.",
        "do_up":    "오늘은 한 가지에 집중해서 끝내기",
        "dont_up":  "여러 일 동시에 벌이기",
        "do_rev":   "잠시 멈춰 목적을 다시 세우기",
        "dont_rev": "방향 모른 채 무작정 밀어붙이기",
    },
    {
        "id": 8, "slug": "strength",
        "name": "Strength", "name_kr": "힘",
        "wiki_file": "RWS_Tarot_08_Strength.jpg",
        "keywords": ["용기", "부드러움", "인내", "내면의 힘"],
        "upright":  "강함은 부드러움에서 나옵니다. 분노와 두려움을 다정하게 다스리면 큰 흐름이 풀립니다.",
        "reversed": "참다 보면 쌓이는 화가 있을 수 있습니다. 안전하게 풀어내는 시간이 필요합니다.",
        "do_up":    "거친 사람에게도 다정한 한마디",
        "dont_up":  "감정을 격하게 폭발시키기",
        "do_rev":   "안전한 곳에서 묵은 감정 풀기",
        "dont_rev": "괜찮은 척 더 참기",
    },
    {
        "id": 9, "slug": "hermit",
        "name": "The Hermit", "name_kr": "은둔자",
        "wiki_file": "RWS_Tarot_09_Hermit.jpg",
        "keywords": ["성찰", "고독", "지혜", "탐구"],
        "upright":  "혼자만의 시간이 큰 답을 가져오는 날입니다. 조용히 생각을 정리하면 길이 보입니다.",
        "reversed": "고립이 너무 길어지면 안 됩니다. 신뢰하는 한 사람과 대화의 문을 열어보세요.",
        "do_up":    "1시간이라도 혼자만의 시간 갖기",
        "dont_up":  "성급하게 답을 내려고 조급해하기",
        "do_rev":   "신뢰하는 한 사람에게 연락하기",
        "dont_rev": "더 깊이 숨고 외면하기",
    },
    {
        "id": 10, "slug": "wheel",
        "name": "Wheel of Fortune", "name_kr": "운명의 수레바퀴",
        "wiki_file": "RWS_Tarot_10_Wheel_of_Fortune.jpg",
        "keywords": ["변화", "순환", "운명", "전환"],
        "upright":  "흐름이 새 단계로 넘어갑니다. 좋은 변화의 신호이니 흐름에 자연스럽게 응답하세요.",
        "reversed": "예상치 못한 변수가 있을 수 있으니 유연한 자세로 임하세요.",
        "do_up":    "새로 들어오는 흐름에 마음 열기",
        "dont_up":  "익숙함만 고집하며 기회 놓치기",
        "do_rev":   "계획 유연하게 수정하기",
        "dont_rev": "변수를 무시한 채 밀어붙이기",
    },
    {
        "id": 11, "slug": "justice",
        "name": "Justice", "name_kr": "정의",
        "wiki_file": "RWS_Tarot_11_Justice.jpg",
        "keywords": ["균형", "진실", "책임", "공정"],
        "upright":  "공정함과 진실이 답이 되는 날입니다. 정직한 결정이 다음 흐름의 토양이 됩니다.",
        "reversed": "감정에 끌려 한쪽으로 기울지 않도록 한 발짝 뒤에서 바라보세요.",
        "do_up":    "껄끄러워도 정직하게 답하기",
        "dont_up":  "상황을 둘러대 책임 회피하기",
        "do_rev":   "한 발짝 떨어져 객관적으로 보기",
        "dont_rev": "감정으로 큰 결정 내리기",
    },
    {
        "id": 12, "slug": "hanged_man",
        "name": "The Hanged Man", "name_kr": "매달린 사람",
        "wiki_file": "RWS_Tarot_12_Hanged_Man.jpg",
        "keywords": ["멈춤", "새 시각", "희생", "통찰"],
        "upright":  "잠시 멈춤이 더 큰 답을 가져옵니다. 익숙한 시각을 뒤집으면 보지 못한 길이 보입니다.",
        "reversed": "기다림이 정체로 굳어지지 않도록 작은 행동을 시작해보세요.",
        "do_up":    "다른 각도로 같은 문제 다시 보기",
        "dont_up":  "익숙한 방식 그대로 반복하기",
        "do_rev":   "오늘 작은 행동 한 가지 시작",
        "dont_rev": "무한정 기다리며 시간만 보내기",
    },
    {
        "id": 13, "slug": "death",
        "name": "Death", "name_kr": "죽음",
        "wiki_file": "RWS_Tarot_13_Death.jpg",
        "keywords": ["종결", "변화", "재생", "전환"],
        "upright":  "끝이 새로운 시작을 부릅니다. 놓아야 할 것을 놓으면 비워진 자리에 새 것이 들어옵니다.",
        "reversed": "변화에 저항하면 더 무거워집니다. 자연스러운 흐름을 받아들이세요.",
        "do_up":    "안 쓰는 것 한 가지 비워내기",
        "dont_up":  "다 쥐고 가려고 안고 있기",
        "do_rev":   "흐름을 인정하고 받아들이기",
        "dont_rev": "변화에 저항하며 시간 끌기",
    },
    {
        "id": 14, "slug": "temperance",
        "name": "Temperance", "name_kr": "절제",
        "wiki_file": "RWS_Tarot_14_Temperance.jpg",
        "keywords": ["균형", "조화", "인내", "치유"],
        "upright":  "서로 다른 것을 부드럽게 섞어내는 하루입니다. 인내와 조율이 가장 큰 무기가 됩니다.",
        "reversed": "한쪽으로 치우친 균형을 되찾을 시간입니다. 휴식이 답입니다.",
        "do_up":    "다른 의견을 일단 듣고 섞어보기",
        "dont_up":  "내 식대로만 끝까지 밀어붙이기",
        "do_rev":   "충분히 쉬고 균형 되찾기",
        "dont_rev": "무리한 일정을 욱여넣기",
    },
    {
        "id": 15, "slug": "devil",
        "name": "The Devil", "name_kr": "악마",
        "wiki_file": "RWS_Tarot_15_Devil.jpg",
        "keywords": ["속박", "유혹", "집착", "그림자"],
        "upright":  "스스로 만든 사슬은 없는지 살펴보세요. 끊어내는 용기가 자유의 시작입니다.",
        "reversed": "오랜 속박에서 벗어나는 흐름이 시작됩니다. 작은 한 걸음이 큰 변화입니다.",
        "do_up":    "끊고 싶은 습관 오늘 한 번만 거르기",
        "dont_up":  "딱 한 번만이라며 합리화",
        "do_rev":   "자유로 가는 작은 한 걸음",
        "dont_rev": "자책으로 다시 묶이기",
    },
    {
        "id": 16, "slug": "tower",
        "name": "The Tower", "name_kr": "탑",
        "wiki_file": "RWS_Tarot_16_Tower.jpg",
        "keywords": ["급격한 변화", "파괴", "진실", "각성"],
        "upright":  "흔들림이 진실을 드러냅니다. 무너진 자리에서 더 단단한 토대를 쌓을 수 있습니다.",
        "reversed": "변화가 임박했다는 신호입니다. 미리 정리할 것은 정리하세요.",
        "do_up":    "흔들리는 부분 인정하고 마주하기",
        "dont_up":  "무너진 것 외면하며 덮기",
        "do_rev":   "미리 정리할 것은 정리하기",
        "dont_rev": "큰 결정 자꾸 미루기",
    },
    {
        "id": 17, "slug": "star",
        "name": "The Star", "name_kr": "별",
        "wiki_file": "RWS_Tarot_17_Star.jpg",
        "keywords": ["희망", "영감", "평온", "치유"],
        "upright":  "어둠 끝의 별빛이 비춥니다. 마음의 상처가 차분히 아물고 새로운 희망이 자라는 날입니다.",
        "reversed": "잠시 길을 잃은 듯해도 별은 꺼지지 않았습니다. 조금만 더 인내하세요.",
        "do_up":    "고마운 사람에게 한마디 전하기",
        "dont_up":  "괜찮은 척 마음 닫기",
        "do_rev":   "조금만 더 인내하기",
        "dont_rev": "희망 자체를 놓아버리기",
    },
    {
        "id": 18, "slug": "moon",
        "name": "The Moon", "name_kr": "달",
        "wiki_file": "RWS_Tarot_18_Moon.jpg",
        "keywords": ["불안", "환상", "직관", "신비"],
        "upright":  "보이지 않는 흐름이 있으니 서두르지 마세요. 직관에 귀 기울이고 한 박자 늦춰보세요.",
        "reversed": "안개가 걷히는 시기입니다. 두려움보다 진실에 집중하세요.",
        "do_up":    "결정 한 박자 늦추고 직관 듣기",
        "dont_up":  "추측만으로 사람·상황 단정",
        "do_rev":   "두려움 대신 사실에 집중하기",
        "dont_rev": "두려움에 끌려 도망치기",
    },
    {
        "id": 19, "slug": "sun",
        "name": "The Sun", "name_kr": "태양",
        "wiki_file": "RWS_Tarot_19_Sun.jpg",
        "keywords": ["기쁨", "성공", "활력", "성취"],
        "upright":  "햇살처럼 환한 하루입니다. 자신 있게 자신을 드러내면 인정과 결실이 따라옵니다.",
        "reversed": "지나친 낙관은 경계하되, 작은 기쁨을 충분히 누리세요.",
        "do_up":    "자신 있게 본인을 드러내기",
        "dont_up":  "겸손이라는 이름으로 숨기",
        "do_rev":   "오늘의 작은 기쁨 충분히 누리기",
        "dont_rev": "근거 없는 낙관으로 일 벌이기",
    },
    {
        "id": 20, "slug": "judgement",
        "name": "Judgement", "name_kr": "심판",
        "wiki_file": "RWS_Tarot_20_Judgement.jpg",
        "keywords": ["깨달음", "부활", "결단", "평가"],
        "upright":  "지난 일을 정리하고 새 부름에 응답할 때입니다. 큰 결단이 새 장을 엽니다.",
        "reversed": "후회가 많은 날일 수 있습니다. 자책보다 한 걸음 앞을 보세요.",
        "do_up":    "미뤄온 결단 오늘 내리기",
        "dont_up":  "또 다음으로 미루기",
        "do_rev":   "자책 끝내고 한 걸음 앞 보기",
        "dont_rev": "후회를 같은 자리에서 반복하기",
    },
    {
        "id": 21, "slug": "world",
        "name": "The World", "name_kr": "세계",
        "wiki_file": "RWS_Tarot_21_World.jpg",
        "keywords": ["완성", "성취", "통합", "여정의 끝"],
        "upright":  "오랜 흐름이 마무리되며 큰 그림이 완성되는 날입니다. 다음 여정을 위한 자축의 시간입니다.",
        "reversed": "마지막 한 걸음이 남았습니다. 마무리 작업을 정성껏 챙기세요.",
        "do_up":    "마무리는 정성껏, 자축도 잊지 말기",
        "dont_up":  "다음 일에 너무 빨리 넘어가기",
        "do_rev":   "남은 마지막 한 걸음 챙기기",
        "dont_rev": "어설프게 끝내고 손 놓기",
    },
]
